<?php

/**
 * @file
 * Contains connecting_links.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function connecting_links_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the connecting_links module.
    case 'help.page.connecting_links':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Entity for connecting links') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function connecting_links_theme() {
  return [
    'connecting_links' => [
      'render element' => 'children',
    ],
  ];
}
